name: dockerize the dotnet application

on:
  push:
    branches: main # [ main ]
  pull_request:
    branches: none # [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build-container:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
     
     
     
     
    - name: Build the Docker image.
      working-directory: 03-app-dotnet
      run: docker build .  -t harshinir/github_actions:latest 
      
    - name: Push the tagged Docker image
      run: docker push harshinir/github_actions:latest
