name: 123-docker-build-workflow

on:
  push:
    branches: main # [ main ]
  pull_request:
    branches: none # [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build-container:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    
    - name: Build the Docker image.
      working-directory: 03-app-dotnet
      run: docker build .  --tag latest 
      
    - name: Push the tagged Docker image
      run: docker push harshinir/github_actions:latest
